version: '3'

services:
  site:
    image: jekyll/jekyll:3.8.6
    container_name: personal_blog
    command: jekyll serve --livereload --verbose
    ports:
      - "4000:4000"
    volumes:
      - ../:/srv/jekyll
      - ../vendor/bundle:/usr/local/bundle